name: 🐞 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How did this happen? (screenshots optional)
      placeholder: 1. Go to '...' 2. Click '...' 3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional context
      description: Logs, system info, ideas for fixes
